language: rust
cache: cargo
os: linux

rust:
  - stable
  - beta
  - nightly

env:
  - RELEASE=
  - RELEASE=--release

arch:
  - amd64
  - arm64
  - ppc64le
  - s390x

jobs:
  include:
    -
      script: cargo test $RELEASE
    - arch: amd64
      script:
        - |
          rustup target add i686-unknown-linux-gnu
          cargo test --target i686-unknown-linux-gnu --target-dir=target/i686
    - arch: amd64
      rust: nightly
      env: RELEASE=--release
      script:
        - \
          set -e
          rustup component add rust-src
          RUSTFLAGS=-Zsanitizer="address" cargo test --release -Zbuild-std --target x86_64-unknown-linux-gnu --target-dir=target/"address"