language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
os: linux
jobs:
  include:
    - arch:
        - amd64
        - ppc64le
        - s390x
        - arm64
      env:
        - RELEASE=
        - RELEASE=--release
      script:
        - cargo test $RELEASE
    - arch:
        - amd64
      env:
        - RELEASE=
        - RELEASE=--release
      addons:
        apt:
          packages:
            - gcc-multilib
      script:
        - |
          set -e
          rustup target add i686-unknown-linux-gnu
          cargo test --release --target i686-unknown-linux-gnu --target-dir=target/i686
    - arch:
        - amd64
      env:
        - SANITIZER=address
        - SANITIZER=memory
        - SANITIZER=thread
        - SANITIZER=leak
      script:
        - |
          set -e
          rustup component add rust-src
          RUSTFLAGS=-Zsanitizer=$SANITIZER cargo test --release -Zbuild-std --target x86_64-unknown-linux-gnu --target-dir=target/$SANITIZER