language: rust
rust:
- stable
- beta
- nightly
matrix:
script:
  - |
    cargo build
    cargo test
    cargo test --release
    if [[ "$TRAVIS_CPU_ARCH" == amd64 ]]
    then
      rustup target add i686-unknown-linux-gnu
      cargo test --target i686-unknown-linux-gnu --target-dir=target/i686
      cargo test --release --target i686-unknown-linux-gnu --target-dir=target/i686
    fi
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]] && [[ "$TRAVIS_CPU_ARCH" == amd64 ]]
    then
      rustup component add rust-src
      RUSTFLAGS=-Zsanitizer=address cargo test --release -Zbuild-std --target x86_64-unknown-linux-gnu --target-dir=target/address
      RUSTFLAGS=-Zsanitizer=thread cargo test --release -Zbuild-std --target x86_64-unknown-linux-gnu --target-dir=target/thread
      RUSTFLAGS=-Zsanitizer=memory cargo test --release -Zbuild-std --target x86_64-unknown-linux-gnu --target-dir=target/memory
      RUSTFLAGS=-Zsanitizer=leak cargo test --release -Zbuild-std --target x86_64-unknown-linux-gnu --target-dir=target/leak
    fi

allow_failures:
- rust: nightly
cache: cargo
arch:
  - amd64
  - ppc64le
  - s390x
  - arm64
os: linux